# Generated by Django 3.1.7 on 2021-03-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210319_0249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Horario',
        ),
        migrations.AddField(
            model_name='consulta',
            name='ocupado',
            field=models.BooleanField(default=False),
        ),
    ]
