# Generated by Django 3.1.7 on 2021-03-19 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210319_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='horario',
            new_name='horarios',
        ),
    ]
