# Generated by Django 3.1.7 on 2021-03-24 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210319_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='horarios',
        ),
        migrations.AddField(
            model_name='consulta',
            name='agenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='horarios', to='api.agenda'),
        ),
    ]
